### ISSUE TITLE
Photo holders not responsive

### ISSUE THREAD

**Issue by pushpdeep** [shubhampk37/shubhampk37.github.io#1]
The page is responsive but the picture is not. it gets stretched vertically

![Screenshot from 2020-05-16 11-22-23](https://user-images.githubusercontent.com/7886419/82112143-e5242b80-9767-11ea-994d-86e641de7a5f.png)

@shubhampk37

**Comment by shubhampk37** [comment]
Now,I have made more changes for the extra small devices.By making it extend the full screen removing all the padding that you can see here.But,it is not possible to get the exact images.I got 138*150 for this mode maximum.Also,since the images are 150*150 too hard to accommodate them in this width of 320px.I tried other modes as well.Works perfect for width greater than 350px without any scaling.

**Comment by shubhampk37** [comment]
Also,I had the doubt of positioning the arrows on devices like phone.Mid-way looks good or needs to changed somewhere?

**Comment by pushpdeep** [comment]
Done
